#ifndef LINE_TRACE_CONFIG_H
#define LINE_TRACE_CONFIG_H

#include "SensorConfig.h"

/* 正規化後のライン境界目標 */
#define TARGET_BRIGHTNESS (etrobo_app::COLOR_SENSOR_NORMALIZED_TARGET_REFLECTION)

/* ステアリング操舵量の係数 */
#define STEERING_COEF     (0.20F)	// 直進のふらつきを抑えるため弱めにする
#define STEERING_KP       (STEERING_COEF)
#define STEERING_KD (0.001F)
#define CONTROL_DT_SEC (0.003F)
#define LINE_TRACER_CONTROL_PERIOD_US (3 * 1000)
#define LINE_TRACER_ERROR_FILTER_ALPHA (0.30F)
#define LINE_TRACER_ERROR_DEADBAND     (3.0F)
#define LINE_TRACER_STEERING_DEADBAND  (5)
#define LINE_TRACER_STRAIGHT_KP        (0.18F)
#define LINE_TRACER_STRAIGHT_STEERING_DEADBAND (6)
#define LINE_TRACER_CURVE_KP           (0.38F)
#define LINE_TRACER_CURVE_DETECT_KP    (0.38F)
#define LINE_TRACER_CURVE_STEERING_DEADBAND (LINE_TRACER_STEERING_DEADBAND)
#define LINE_TRACER_CURVE_TURN_BOOST_MIN (8)
#define LINE_TRACER_CURVE_TURN_GAIN      (1.40F)
#define LINE_TRACER_CURVE_DETECT_TURN_BOOST_MIN (8)
#define LINE_TRACER_CURVE_DETECT_TURN_GAIN      (1.6F)
#define LINE_TRACER_LEFT_CURVE_TURN_GAIN  (1.15F)
#define LINE_TRACER_RIGHT_CURVE_TURN_GAIN (1.05F)

/* 直線/カーブ判定のIMU補助 */
#define LINE_TRACER_IMU_PATH_DETECTION_ENABLE (1)
#define LINE_TRACER_IMU_CURVE_YAW_RATE_MIN    (18.0F)
#define LINE_TRACER_IMU_CURVE_STEERING_MIN    (6)
#define LINE_TRACER_IMU_STRAIGHT_YAW_RATE_MAX (15.0F)

/* 直進判定中だけ使うIMU揺れ止め補正 */
#define LINE_TRACER_STRAIGHT_IMU_CORRECTION_ENABLE (1)
#define LINE_TRACER_STRAIGHT_IMU_YAW_RATE_GAIN     (0.12F)
#define LINE_TRACER_STRAIGHT_IMU_YAW_RATE_FILTER_ALPHA (0.20F)
#define LINE_TRACER_STRAIGHT_IMU_CORRECTION_LIMIT  (6)
#define LINE_TRACER_STRAIGHT_IMU_LINE_TURN_MAX     (12)

/* 走行基準power */
#define LINE_TRACER_STRAIGHT_BASE_POWER (90)  // 直線時の基準power
#define LINE_TRACER_GENTLE_CURVE_BASE_POWER (75)  // ゆるいカーブの基準power
#define LINE_TRACER_NORMAL_CURVE_BASE_POWER (65)  // 普通カーブの基準power
#define LINE_TRACER_SHARP_CURVE_BASE_POWER  (45)  // きついカーブの基準power
#define BASE_SPEED        (LINE_TRACER_STRAIGHT_BASE_POWER)

/* ライントレースエッジ切り替え
 * この機体では -1 がライン左側を沿う補正向き、1 が反対側の補正向き。
 */
#define LEFT_EDGE         (-1)
#define RIGHT_EDGE        (1)
#define TRACE_EDGE        (LEFT_EDGE)

/* モータ出力の上限 */
#define MOTOR_POWER_MAX   (100)
#define MOTOR_POWER_MIN   (-100)

/* 走行状態判定 */
#define LINE_TRACER_PATH_UNKNOWN       (0)
#define LINE_TRACER_PATH_STRAIGHT      (1)
#define LINE_TRACER_PATH_CURVE         (2)
#define LINE_TRACER_CURVE_LEVEL_NONE   (0)
#define LINE_TRACER_CURVE_LEVEL_GENTLE (1)
#define LINE_TRACER_CURVE_LEVEL_NORMAL (2)
#define LINE_TRACER_CURVE_LEVEL_SHARP  (3)
#define LINE_TRACER_CURVE_STEERING_MIN (16)
#define LINE_TRACER_NORMAL_CURVE_STEERING_MIN (22)
#define LINE_TRACER_SHARP_CURVE_STEERING_MIN  (34)
#define LINE_TRACER_STRAIGHT_STEERING_MAX (10)
#define LINE_TRACER_CURVE_DERIVATIVE_MIN  (2400.0F)
#define LINE_TRACER_STRAIGHT_DERIVATIVE_MAX (1200.0F)
#define LINE_TRACER_CURVE_DETECT_COUNT (3)
#define LINE_TRACER_STRAIGHT_DETECT_COUNT (15)

#endif
